services:
  - type: web
    name: kv-digital-cinema-backend
    runtime: node
    plan: free
    buildCommand: npm install && npm run build
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000
      - key: DATABASE_URL
        value: file:./dev.db
      - key: JWT_SECRET
        generateValue: true
      - key: JWT_REFRESH_SECRET
        generateValue: true
      - key: JWT_EXPIRES_IN
        value: 7d
      - key: JWT_REFRESH_EXPIRES_IN
        value: 30d
      - key: FRONTEND_URL
        sync: false
      - key: ABA_PAYWAY_API_URL
        value: https://checkout-sandbox.payway.com.kh/api/payment-gateway/v1/payments/purchase
      - key: ABA_PAYWAY_MERCHANT_ID
        value: ec477410
      - key: ABA_PAYWAY_API_KEY
        value: 80cb36f0ebc28ba5f33eef0f030404bdf13e0ac2
      - key: ABA_PAYWAY_SECRET
        value: 80cb36f0ebc28ba5f33eef0f030404bdf13e0ac2
      - key: BAKONG_API_URL
        value: https://api-bakong.nbc.gov.kh/v1
      - key: BAKONG_BEARER_TOKEN
        value: rbkcHfsm5XrVlb1CXFYHiudZDEyK3gIDUM-WwL9GNzfUpg
      - key: BAKONG_ACCOUNT_ID
        value: thy_seng1@bkrt
      - key: BAKONG_MERCHANT_NAME
        value: KV Digital Cinema
      - key: CUTLUY_API_KEY
        value: ck_live_QuVCpMzXMhvf5jUobZ6Z85OtsXpGW_FS
      - key: CUTLUY_API_URL
        value: https://cutluy.com/v1/payments
      - key: CUTLUY_ACCOUNT_ID
        value: abaakhppxxx@abaa
      - key: CUTLUY_MERCHANT_NAME
        value: KV Digital Cinema
